const LEVEL_PRIORITY = {
  soft: 1,
  warning: 2,
  block: 3,
};

export const CONTENT_SAFETY_WORDS = [
  { word: "홍보합니다", category: "spam", level: "soft" },
  { word: "홍보글", category: "spam", level: "soft" },
  { word: "광고", category: "spam", level: "soft" },
  { word: "스팸", category: "spam", level: "soft" },
  { word: "무료 이벤트", category: "spam", level: "soft" },
  { word: "무료 증정", category: "spam", level: "soft" },
  { word: "무료 체험", category: "spam", level: "soft" },
  { word: "공짜로 드려요", category: "spam", level: "soft" },
  { word: "선착순 증정", category: "spam", level: "soft" },
  { word: "한정 수량", category: "spam", level: "soft" },
  { word: "팔로우 이벤트", category: "spam", level: "soft" },
  { word: "좋아요 이벤트", category: "spam", level: "soft" },
  { word: "댓글 이벤트", category: "spam", level: "soft" },
  { word: "클릭하세요", category: "spam", level: "soft" },
  { word: "클릭해주세요", category: "spam", level: "soft" },
  { word: "바로가기", category: "spam", level: "soft" },
  { word: "click here", category: "spam", level: "soft" },
  { word: "clickhere", category: "spam", level: "soft" },
  { word: "buy now", category: "spam", level: "soft" },
  { word: "limited offer", category: "spam", level: "soft" },
  { word: "act now", category: "spam", level: "soft" },
  { word: "sign up now", category: "spam", level: "soft" },
  { word: "subscribe now", category: "spam", level: "soft" },
  { word: "free gift", category: "spam", level: "soft" },
  { word: "free trial", category: "spam", level: "soft" },
  { word: "giveaway", category: "spam", level: "soft" },
  { word: "give away", category: "spam", level: "soft" },
  { word: "과대광고", category: "misleading", level: "soft" },
  { word: "효과 보장", category: "misleading", level: "soft" },
  { word: "100% 효과", category: "misleading", level: "soft" },
  { word: "misleading", category: "misleading", level: "soft" },
  { word: "offensive", category: "misleading", level: "soft" },
  { word: "ㅅㅂ", category: "profanity", level: "warning" },
  { word: "ㅂㅅ", category: "profanity", level: "warning" },
  { word: "ㅁㅊ", category: "profanity", level: "warning" },
  { word: "ㄲㅈ", category: "profanity", level: "warning" },
  { word: "ㅈㄹ", category: "profanity", level: "warning" },
  { word: "ㅈㄴ", category: "profanity", level: "warning" },
  { word: "ㅅㄲ", category: "profanity", level: "warning" },
  { word: "ㄷㅊ", category: "profanity", level: "warning" },
  { word: "ㄱㄲ", category: "profanity", level: "warning" },
  { word: "ㅆㅂ", category: "profanity", level: "warning" },
  { word: "ㅃㅅ", category: "profanity", level: "warning" },
  { word: "시발", category: "profanity", level: "warning" },
  { word: "씨발", category: "profanity", level: "warning" },
  { word: "씨팔", category: "profanity", level: "warning" },
  { word: "시팔", category: "profanity", level: "warning" },
  { word: "씨바", category: "profanity", level: "warning" },
  { word: "시바", category: "profanity", level: "warning" },
  { word: "시1발", category: "profanity", level: "warning" },
  { word: "씨1발", category: "profanity", level: "warning" },
  { word: "s발", category: "profanity", level: "warning" },
  { word: "c발", category: "profanity", level: "warning" },
  { word: "병신", category: "profanity", level: "warning" },
  { word: "병1신", category: "profanity", level: "warning" },
  { word: "개같은", category: "profanity", level: "warning" },
  { word: "개새끼", category: "profanity", level: "warning" },
  { word: "개년", category: "profanity", level: "warning" },
  { word: "개놈", category: "profanity", level: "warning" },
  { word: "개쓰레기", category: "profanity", level: "warning" },
  { word: "좆밥", category: "profanity", level: "warning" },
  { word: "ㅈ밥", category: "profanity", level: "warning" },
  { word: "좆같은", category: "profanity", level: "warning" },
  { word: "ㅈ같은", category: "profanity", level: "warning" },
  { word: "찐따", category: "profanity", level: "warning" },
  { word: "미친놈", category: "profanity", level: "warning" },
  { word: "미친년", category: "profanity", level: "warning" },
  { word: "미친새끼", category: "profanity", level: "warning" },
  { word: "창녀", category: "profanity", level: "warning" },
  { word: "걸레년", category: "profanity", level: "warning" },
  { word: "변태새끼", category: "profanity", level: "warning" },
  { word: "쓰레기같은", category: "profanity", level: "warning" },
  { word: "보지", category: "profanity", level: "warning" },
  { word: "자지", category: "profanity", level: "warning" },
  { word: "fuck", category: "profanity", level: "warning" },
  { word: "fucking", category: "profanity", level: "warning" },
  { word: "fucked", category: "profanity", level: "warning" },
  { word: "fucker", category: "profanity", level: "warning" },
  { word: "f*ck", category: "profanity", level: "warning" },
  { word: "fck", category: "profanity", level: "warning" },
  { word: "shit", category: "profanity", level: "warning" },
  { word: "shitty", category: "profanity", level: "warning" },
  { word: "bullshit", category: "profanity", level: "warning" },
  { word: "damn", category: "profanity", level: "warning" },
  { word: "dumbass", category: "profanity", level: "warning" },
  { word: "idiot", category: "profanity", level: "warning" },
  { word: "moron", category: "profanity", level: "warning" },
  { word: "wtf", category: "profanity", level: "warning" },
  { word: "stfu", category: "profanity", level: "warning" },
  { word: "gtfo", category: "profanity", level: "warning" },
  { word: "bitch", category: "profanity", level: "warning" },
  { word: "bastard", category: "profanity", level: "warning" },
  { word: "asshole", category: "profanity", level: "warning" },
  { word: "ass hole", category: "profanity", level: "warning" },
  { word: "motherfucker", category: "profanity", level: "warning" },
  { word: "son of a bitch", category: "profanity", level: "warning" },
  { word: "retard", category: "profanity", level: "warning" },
  { word: "cunt", category: "profanity", level: "warning" },
  { word: "dick", category: "profanity", level: "warning" },
  { word: "cock", category: "profanity", level: "warning" },
  { word: "pussy", category: "profanity", level: "warning" },
  { word: "돈 벌기", category: "fraud", level: "warning" },
  { word: "돈버는 방법", category: "fraud", level: "warning" },
  { word: "부업 추천", category: "fraud", level: "warning" },
  { word: "재택 부업", category: "fraud", level: "warning" },
  { word: "고수익 보장", category: "fraud", level: "warning" },
  { word: "수익 인증", category: "fraud", level: "warning" },
  { word: "월 천만원", category: "fraud", level: "warning" },
  { word: "투자 권유", category: "fraud", level: "warning" },
  { word: "코인 추천", category: "fraud", level: "warning" },
  { word: "주식 추천", category: "fraud", level: "warning" },
  { word: "비트코인 투자", category: "fraud", level: "warning" },
  { word: "급전 대출", category: "fraud", level: "warning" },
  { word: "불법 대출", category: "fraud", level: "warning" },
  { word: "즉시 입금", category: "fraud", level: "warning" },
  { word: "카카오톡 추가", category: "fraud", level: "warning" },
  { word: "오픈채팅 초대", category: "fraud", level: "warning" },
  { word: "텔레그램 초대", category: "fraud", level: "warning" },
  { word: "free money", category: "fraud", level: "warning" },
  { word: "earn money fast", category: "fraud", level: "warning" },
  { word: "make money online", category: "fraud", level: "warning" },
  { word: "guaranteed profit", category: "fraud", level: "warning" },
  { word: "investment opportunity", category: "fraud", level: "warning" },
  { word: "work from home", category: "fraud", level: "warning" },
  { word: "passive income", category: "fraud", level: "warning" },
  { word: "crypto giveaway", category: "fraud", level: "warning" },
  { word: "nft giveaway", category: "fraud", level: "warning" },
  { word: "scam", category: "fraud", level: "warning" },
  { word: "phishing", category: "fraud", level: "warning" },
  { word: "gift card", category: "fraud", level: "warning" },
  { word: "wire transfer", category: "fraud", level: "warning" },
  { word: "send money", category: "fraud", level: "warning" },
  { word: "꺼져", category: "harassment", level: "warning" },
  { word: "닥쳐", category: "harassment", level: "warning" },
  { word: "뒤져", category: "harassment", level: "warning" },
  { word: "찐따같은", category: "harassment", level: "warning" },
  { word: "정신병자", category: "harassment", level: "warning" },
  { word: "장애인 취급", category: "harassment", level: "warning" },
  { word: "틀딱", category: "hate", level: "warning" },
  { word: "맘충", category: "hate", level: "warning" },
  { word: "한남충", category: "hate", level: "warning" },
  { word: "김치녀", category: "hate", level: "warning" },
  { word: "인종차별", category: "hate", level: "warning" },
  { word: "차별 발언", category: "hate", level: "warning" },
  { word: "지금 바로 신청", category: "spam", level: "warning" },
  { word: "지금 신청하세요", category: "spam", level: "warning" },
  { word: "지금 구매하세요", category: "spam", level: "warning" },
  { word: "exclusive deal", category: "spam", level: "warning" },
  { word: "개인정보 입력", category: "privacy", level: "warning" },
  { word: "자살해", category: "self_harm", level: "block" },
  { word: "죽어버려", category: "self_harm", level: "block" },
  { word: "꺼져 죽어", category: "self_harm", level: "block" },
  { word: "자해해", category: "self_harm", level: "block" },
  { word: "스스로 목숨", category: "self_harm", level: "block" },
  { word: "kill yourself", category: "self_harm", level: "block" },
  { word: "kys", category: "self_harm", level: "block" },
  { word: "end your life", category: "self_harm", level: "block" },
  { word: "self harm", category: "self_harm", level: "block" },
  { word: "cut yourself", category: "self_harm", level: "block" },
  { word: "죽여버리겠다", category: "violence", level: "block" },
  { word: "찾아가서 죽여", category: "violence", level: "block" },
  { word: "칼로 찌를게", category: "violence", level: "block" },
  { word: "폭탄 설치", category: "violence", level: "block" },
  { word: "i will kill you", category: "violence", level: "block" },
  { word: "death threat", category: "violence", level: "block" },
  { word: "bomb threat", category: "violence", level: "block" },
  { word: "성희롱", category: "sexual", level: "block" },
  { word: "성추행", category: "sexual", level: "block" },
  { word: "강간해", category: "sexual", level: "block" },
  { word: "강간할게", category: "sexual", level: "block" },
  { word: "rape", category: "sexual", level: "block" },
  { word: "계좌번호 보내", category: "privacy", level: "block" },
  { word: "주민번호 알려줘", category: "privacy", level: "block" },
  { word: "비밀번호 보내줘", category: "privacy", level: "block" },
  { word: "신용카드 번호", category: "privacy", level: "block" },
  { word: "본인인증 링크", category: "privacy", level: "block" },
  { word: "혐오 발언", category: "hate", level: "block" },
  { word: "인종 비하", category: "hate", level: "block" },
  { word: "장애인 비하", category: "hate", level: "block" },
];

export const DEFAULT_HIDDEN_WORDS = CONTENT_SAFETY_WORDS.map((item) => item.word);

function normalizeEntry(entry) {
  if (typeof entry === "string") {
    return { word: entry.trim().toLowerCase(), category: "custom", level: "soft" };
  }

  return {
    word: String(entry?.word || "").trim().toLowerCase(),
    category: entry?.category || "custom",
    level: entry?.level || "soft",
  };
}

export function normalizeHiddenWords(words = DEFAULT_HIDDEN_WORDS) {
  return words
    .map((entry) => normalizeEntry(entry).word)
    .filter(Boolean);
}

export function findContentSafetyMatches(text = "", entries = CONTENT_SAFETY_WORDS) {
  const normalizedText = String(text || "").toLowerCase();
  if (!normalizedText) return [];

  return entries
    .map(normalizeEntry)
    .filter((entry) => entry.word && normalizedText.includes(entry.word));
}

export function evaluateContentSafety(text = "", entries = CONTENT_SAFETY_WORDS) {
  const matches = findContentSafetyMatches(text, entries);
  const level = matches.reduce((highest, entry) => {
    return LEVEL_PRIORITY[entry.level] > LEVEL_PRIORITY[highest] ? entry.level : highest;
  }, "soft");

  return {
    matches,
    level: matches.length > 0 ? level : null,
    blocked: matches.some((entry) => entry.level === "block"),
    warning: matches.some((entry) => entry.level === "warning"),
  };
}

export function containsHiddenWord(text = "", words = DEFAULT_HIDDEN_WORDS) {
  const entries = Array.isArray(words) && words.length > 0 ? words : DEFAULT_HIDDEN_WORDS;
  return findContentSafetyMatches(text, entries).length > 0;
}
