export const PRESENTATION_GROUPS = [
  {
    id: "overview",
    speaker: "광재",
    title: "프로젝트 전체 소개",
    duration: "4~5분",
    appPath: "/admin",
    summary: "repo 구조, PR 규칙, 협업 방식, DB 초기화, admin, story 위치를 빠르게 짚는 파트",
    sections: [
      {
        id: "tree",
        label: "Tree 구조",
        kind: "구조",
        file: "kosa-biz-team3/{app,server,docs}",
        language: "markdown",
        talkingPoints: ["최상위 폴더는 멀티 repo 컨테이너", "app은 Vite React, server는 Spring Boot + MyBatis + Oracle", "docs/http는 API 수동 검증과 협업 문서 위치"],
        code: `kosa-biz-team3/
├── app/                         # Vite + React frontend
│   ├── src/api/                 # REST API client wrappers
│   ├── src/components/          # modal, navigation, panel 공통 UI
│   ├── src/features/            # feed, post, profile, story, auth
│   └── src/routes/AppRoutes.jsx # protected route + page mapping
├── server/                      # Spring Boot backend
│   ├── src/main/java/com/bizteam3/server
│   │   ├── global/auth          # JWT, interceptor
│   │   ├── post                 # feed/detail/comment/like
│   │   ├── follows              # follow/follow request
│   │   ├── notification         # notification domain
│   │   ├── story                # story + story views
│   │   └── user/profile         # user CRUD + profile
│   └── src/main/resources
│       ├── db/                  # Oracle DDL + seed scripts
│       └── mybatis/mapper       # DAO XML queries
└── docs/                        # HTTP examples / handoff notes`,
      },
      {
        id: "routes",
        label: "프론트 라우팅",
        kind: "Frontend",
        file: "app/src/routes/AppRoutes.jsx",
        language: "javascript",
        talkingPoints: ["로그인 외 화면은 ProtectedRoute 안쪽", "피드, 프로필, 관리자, 설정을 AppShell 레이아웃으로 공유", "발표 시 admin 위치도 여기서 설명"],
        code: `export function AppRoutes() {
  return (
    <Routes>
      <Route path="/login" element={<LoginPage />} />
      <Route
        element={
          <ProtectedRoute>
            <AppShell />
          </ProtectedRoute>
        }
      >
        <Route path="/" element={<FeedPage />} />
        <Route path="/profile" element={<ProfilePage />} />
        <Route path="/profile/:username" element={<ProfilePage />} />
        <Route path="/admin" element={<UserCrudPage />} />
        <Route path="/settings" element={<SettingsPage />} />
      </Route>
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  );
}`,
      },
      {
        id: "db",
        label: "DB 초기화",
        kind: "DB",
        file: "server/src/main/resources/db/*.sql",
        language: "sql",
        talkingPoints: ["Oracle DDL은 도메인별 파일로 분리", "users, posts, medias, comments, follows, notifications, stories 순서로 설명", "story는 stories와 story_views로 나뉨"],
        code: `CREATE TABLE users (
  user_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username VARCHAR2(50 CHAR) NOT NULL,
  password VARCHAR2(255 CHAR) NOT NULL,
  name VARCHAR2(80 CHAR) NOT NULL,
  bio CLOB,
  profile_img VARCHAR2(1000 CHAR),
  account_vis VARCHAR2(20 CHAR) DEFAULT 'PUBLIC' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  delete_at TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (user_id),
  CONSTRAINT ck_users_account_vis CHECK (account_vis IN ('PUBLIC', 'PRIVATE'))
);

CREATE TABLE stories (
  story_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  user_id NUMBER(19) NOT NULL,
  image_url VARCHAR2(1000 CHAR) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_stories PRIMARY KEY (story_id),
  CONSTRAINT fk_stories_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);`,
      },
    ],
  },
  {
    id: "feed",
    speaker: "혁준",
    title: "로그인 이후 메인 피드 흐름",
    duration: "6~7분",
    appPath: "/",
    summary: "JWT 로그인 후 피드 API, 게시글 카드, 좋아요, 저장, 해시태그 흐름을 보여주는 파트",
    sections: [
      {
        id: "jwt",
        label: "JWT 로그인",
        kind: "Backend",
        file: "server/src/main/java/.../AuthController.java + JwtServiceImpl.java",
        language: "java",
        talkingPoints: ["POST /api/auth/login에서 accessToken 발급", "프론트는 토큰과 사용자 정보를 저장", "이후 API는 AccessTokenCheck 인터셉터 흐름"],
        code: `@RestController
@RequestMapping("/api/auth")
public class AuthController {
  @PostMapping("/login")
  public LoginResponse login(@RequestBody LoginRequest request) {
    return authService.login(request);
  }

  @GetMapping("/me")
  @AccessTokenCheck
  public GetMeResponse me(HttpServletRequest request) {
    String authorization = request.getHeader("Authorization");
    String token = authorization.substring(7).trim();
    return authService.getMe(token);
  }
}

public String createJwt(Integer userId, String username, String name) {
  return Jwts.builder()
      .subject(String.valueOf(userId))
      .claim("username", username)
      .claim("name", name)
      .id(UUID.randomUUID().toString())
      .expiration(getExpiration(jwtProperties.accessTokenExpirationMs()))
      .signWith(getSigningKey())
      .compact();
}`,
      },
      {
        id: "feed-api",
        label: "Post Feed",
        kind: "Frontend",
        file: "app/src/features/feed/FeedPage.jsx + app/src/api/postsApi.js",
        language: "javascript",
        talkingPoints: ["getFeedPosts(page, size)로 페이지 기반 피드 로딩", "IntersectionObserver로 무한 스크롤", "Story와 Feed를 같은 첫 화면에서 로드"],
        code: `export async function getFeedPosts({ page = 0, size = 10 } = {}) {
  const params = new URLSearchParams({
    page: String(page),
    size: String(size),
  });

  return apiRequest("/api/posts/feed?" + params.toString());
}

const loadFeedPage = useCallback(async (targetPage = 0, mode = "replace") => {
  if (loadingRef.current) return;
  loadingRef.current = true;
  setLoading(true);

  try {
    const feed = await getFeedPosts({ page: targetPage, size: 10 });
    setPosts((current) => (mode === "append" ? [...current, ...feed.content] : feed.content));
    setPage(feed.pageRequest.page);
    setHasNext(feed.hasNext);
  } finally {
    setLoading(false);
    loadingRef.current = false;
  }
}, [t]);`,
      },
      {
        id: "post-actions",
        label: "Like / Bookmark",
        kind: "Frontend",
        file: "app/src/features/post/PostCard.jsx",
        language: "javascript",
        talkingPoints: ["좋아요와 북마크는 API 호출 후 상위 feed reload", "상태 변경은 카드 내부 UI와 서버 상태를 맞추는 방식", "해시태그는 caption 텍스트와 post_hashtags 테이블로 연결"],
        code: `const toggleLike = async () => {
  setActionError("");
  try {
    if (post.likedByMe) await unlikePost(post.postId);
    else await likePost(post.postId);
    onChanged();
  } catch {
    setActionError(t("postActionFailed"));
  }
};

const toggleSave = async () => {
  setActionError("");
  try {
    if (post.savedByMe) await unsavePost(post.postId);
    else await savePost(post.postId);
    onChanged();
  } catch {
    setActionError(t("postActionFailed"));
  }
};`,
      },
      {
        id: "feed-mybatis",
        label: "Feed MyBatis",
        kind: "MyBatis",
        file: "server/src/main/resources/mybatis/mapper/PostDao.xml",
        language: "xml",
        talkingPoints: ["공개 계정 또는 팔로우 관계가 있는 계정의 게시글만 노출", "liked_byme, saved_byme, is_owner를 SQL에서 계산", "Oracle OFFSET/FETCH로 페이지 처리"],
        code: `<select id="selectFeedPosts"
        resultType="com.bizteam3.server.post.dao.row.FeedPostRow">
  SELECT
    p.post_id,
    u.user_id,
    u.username,
    u.profile_img AS profile_image_url,
    p.caption,
    (
      SELECT COUNT(*)
      FROM likes l
      WHERE l.post_id = p.post_id
    ) AS like_count,
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM saves s
        WHERE s.post_id = p.post_id
          AND s.user_id = #{viewerId}
      ) THEN 1 ELSE 0
    END AS saved_byme
  FROM posts p
  JOIN users u ON u.user_id = p.user_id AND u.delete_at IS NULL
  WHERE p.delete_at IS NULL
    AND (u.account_vis = 'PUBLIC' OR EXISTS (
      SELECT 1 FROM follows f
      WHERE f.follower_user_id = #{viewerId}
        AND f.following_user_id = p.user_id
    ))
  ORDER BY p.created_at DESC
  OFFSET #{offset} ROWS FETCH NEXT #{size} ROWS ONLY
</select>`,
      },
    ],
  },
  {
    id: "detail-profile",
    speaker: "영우",
    title: "게시글 상세와 사용자 화면",
    duration: "6~7분",
    appPath: "/",
    summary: "Post detail 모달, 댓글 페이지네이션, Profile 화면과 게시글 그리드를 설명하는 파트",
    sections: [
      {
        id: "post-detail",
        label: "Post Detail",
        kind: "Frontend",
        file: "app/src/features/post/PostDetailModal.jsx",
        language: "javascript",
        talkingPoints: ["상세 모달 진입 시 게시글 상세와 댓글 첫 페이지를 병렬 로드", "미디어 영역과 댓글/액션 영역을 분리", "모바일에서는 작성자 헤더가 이미지 위에 배치"],
        code: `const load = async () => {
  setError("");
  try {
    const [postResult, commentResult] = await Promise.all([
      getPostDetail(postId),
      getPostComments(postId, { page: 0, size: COMMENTS_PAGE_SIZE }),
    ]);

    setPost(postResult);
    setComments(commentResult.content);
    setCommentPage(commentResult.pageRequest.page);
    setCommentsHasNext(commentResult.hasNext);
  } catch {
    setError(t("postLoadFailed"));
  }
};`,
      },
      {
        id: "comment-scroll",
        label: "댓글 무한스크롤",
        kind: "Frontend",
        file: "app/src/features/post/PostDetailModal.jsx + app/src/api/commentsApi.js",
        language: "javascript",
        talkingPoints: ["댓글은 /api/posts/{postId}/comments?page&size", "모달 내부 scroll root에 sentinel을 둠", "다음 페이지는 기존 댓글 배열 뒤에 append"],
        code: `export async function getPostComments(postId, { page = 0, size = 20 } = {}) {
  const params = new URLSearchParams({
    page: String(page),
    size: String(size),
  });
  const result = await apiRequest("/api/posts/" + postId + "/comments?" + params.toString());

  return {
    content: (result.content || []).map(toComment),
    pageRequest: result.pageRequest || { page, size },
    hasNext: Boolean(result.hasNext),
  };
}

const observer = new IntersectionObserver(
  ([entry]) => {
    if (entry.isIntersecting) loadNextComments();
  },
  { root: commentsScrollRef.current, rootMargin: "120px" },
);`,
      },
      {
        id: "profile",
        label: "Profile",
        kind: "Frontend",
        file: "app/src/features/profile/ProfilePage.jsx",
        language: "javascript",
        talkingPoints: ["username route가 있으면 타인 프로필, 없으면 내 프로필", "게시글/저장됨 탭과 스토리 번들 로드", "프로필 게시글도 IntersectionObserver로 추가 로드"],
        code: `const load = useCallback(async () => {
  const nextProfile = username
    ? await getProfileByUsername(username)
    : await getMyProfile();

  setProfile(nextProfile);

  const [postResult, storyResult] = await Promise.allSettled([
    getProfilePosts(nextProfile.userId, {
      page: 0,
      size: PROFILE_POST_PAGE_SIZE,
      type: getAllowedProfileContentType(nextProfile, contentType),
    }),
    getStoryBundle(nextProfile.userId),
  ]);

  setStories(storyResult.status === "fulfilled" ? storyResult.value.stories : []);
  setPosts(postResult.status === "fulfilled" ? postResult.value.content : []);
}, [contentType, feedVersion, t, username]);`,
      },
      {
        id: "comment-backend",
        label: "Comment API",
        kind: "Backend",
        file: "server/src/main/java/.../CommentController.java",
        language: "java",
        talkingPoints: ["댓글 목록, 생성, 수정, 삭제가 post 하위 route로 묶임", "PageRequest를 재사용해서 page/size를 통일", "AccessTokenCheck로 현재 userId를 request attribute에서 꺼냄"],
        code: `@RestController
@RequestMapping("/api/posts")
@RequiredArgsConstructor
public class CommentController {
  private final CommentService service;

  @GetMapping("/{postId}/comments")
  @AccessTokenCheck
  public PageResponse<CommentResponse> getComments(
      @PathVariable Integer postId,
      PageRequest request,
      HttpServletRequest httpServletRequest
  ) {
    Integer userId = (Integer) httpServletRequest.getAttribute("userId");
    return service.findComments(postId, userId, request);
  }

  @PostMapping("/{postId}/comments")
  @AccessTokenCheck
  public void createComment(
      @PathVariable Integer postId,
      @Valid @RequestBody CommentCreateRequest request,
      HttpServletRequest httpServletRequest
  ) {
    Integer userId = (Integer) httpServletRequest.getAttribute("userId");
    service.create(postId, userId, request);
  }
}`,
      },
    ],
  },
  {
    id: "polish",
    speaker: "우수",
    title: "관계 / 알림 / 프론트 polish",
    duration: "7~8분",
    appPath: "/profile",
    summary: "Follow, following, notification, hidden words, 전체 UX 수정 포인트를 시연하는 파트",
    sections: [
      {
        id: "follow",
        label: "Follow / Following",
        kind: "Fullstack",
        file: "app/src/api/followsApi.js + server/.../FollowServiceImpl.java",
        language: "java",
        talkingPoints: ["공개 계정은 follows에 바로 insert", "비공개 계정은 follow_requests에 PENDING 생성", "viewerRelation으로 버튼 상태를 통일"],
        code: `public void follow(Integer followerUserId, Integer targetUserId) {
  validateDifferentUser(followerUserId, targetUserId);
  User target = getActiveUser(targetUserId);

  if (target.getAccountVis() == AccountVisType.PRIVATE) {
    sendFollowRequest(followerUserId, targetUserId);
  } else {
    followDirectly(followerUserId, targetUserId);
  }
}

private void followDirectly(Integer followerUserId, Integer followingUserId) {
  if (followDao.countByUsers(followerUserId, followingUserId) > 0) {
    return; // 이미 팔로우 중이면 멱등 처리
  }
  followDao.insert(new Follow(followerUserId, followingUserId));
}`,
      },
      {
        id: "notification",
        label: "Notification",
        kind: "Frontend",
        file: "app/src/components/panels/NotificationPanel.jsx",
        language: "javascript",
        talkingPoints: ["알림과 팔로우 요청을 동시에 로드", "읽음 처리 후 화면과 badge 동기화", "알림에서 바로 프로필/게시글 상세로 이동"],
        code: `const load = async () => {
  setLoading(true);
  setError("");
  try {
    const [notificationResult, requestResult] = await Promise.all([
      getNotifications(),
      getFollowRequests(),
    ]);
    setNotifications(notificationResult.notifications);
    setRequests(requestResult.requests);
    setLoadedAt(Date.now());
  } catch {
    setError(t("notificationsLoadFailed"));
  } finally {
    setLoading(false);
  }
};

const handleNotificationClick = async () => {
  if (!hasUnreadNotifications) return;
  await markNotificationsRead();
  setNotifications((current) =>
    current.map((notification) => ({ ...notification, read: true })),
  );
  await onChanged?.();
};`,
      },
      {
        id: "notification-mybatis",
        label: "Notification MyBatis",
        kind: "MyBatis",
        file: "server/src/main/resources/mybatis/mapper/NotificationDao.xml",
        language: "xml",
        talkingPoints: ["LIKE 알림은 같은 게시글 이벤트를 하나로 묶음", "target_image_url은 게시글 첫 미디어를 가져옴", "viewer_relation을 SQL에서 계산해 프론트 버튼에 전달"],
        code: `<select id="selectByReceiverUserId" resultMap="notificationResponseMap">
  SELECT
    n.notification_id,
    n.actor_user_id,
    u.username AS actor_username,
    n.notification_type AS type,
    CASE
      WHEN n.target_type = 'POST' THEN COALESCE((
        SELECT m.media_url
        FROM medias m
        WHERE m.post_id = n.target_id
        ORDER BY m.sort_order ASC, m.media_id ASC
        FETCH FIRST 1 ROWS ONLY
      ), n.image_url)
      ELSE NULL
    END AS target_image_url,
    CASE
      WHEN n.actor_user_id = #{receiverUserId} THEN 'SELF'
      WHEN EXISTS (
        SELECT 1 FROM follows f
        WHERE f.follower_user_id = #{receiverUserId}
          AND f.following_user_id = n.actor_user_id
      ) THEN 'FOLLOWING'
      ELSE 'NOT_FOLLOWING'
    END AS viewer_relation
  FROM notifications n
  LEFT JOIN users u ON u.user_id = n.actor_user_id
  WHERE n.receiver_user_id = #{receiverUserId}
  ORDER BY n.created_at DESC
</select>`,
      },
      {
        id: "hidden-words",
        label: "Hidden Words",
        kind: "Frontend",
        file: "app/src/utils/hiddenWords.js + PostCard.jsx",
        language: "javascript",
        talkingPoints: ["숨긴 단어 설정은 preferences 이벤트로 반영", "caption/comment에 containsHiddenWord 적용", "경고/차단 레벨은 evaluateContentSafety가 결정"],
        code: `export function containsHiddenWord(text = "", words = []) {
  const normalizedText = normalizeText(text);
  return words.some((word) => {
    const normalizedWord = normalizeText(word);
    return normalizedWord && normalizedText.includes(normalizedWord);
  });
}

useEffect(() => {
  const loadPreferences = () => {
    getPreferences().then((preferences) => {
      setHiddenWordsEnabled(Boolean(preferences.hiddenWordsEnabled));
      setHiddenWords(preferences.hiddenWords || []);
      setContentRevealed(false);
    });
  };

  loadPreferences();
  window.addEventListener("preferences:changed", loadPreferences);
  return () => window.removeEventListener("preferences:changed", loadPreferences);
}, []);`,
      },
    ],
  },
];
